# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               箐珉布业
tagline:             '涤丝磨毛花布、绿布'
description:         '主营涤丝磨毛花布、绿布、定织定染'
url:                 http://qmby.github.io/
baseurl:             '/qmby'
paginate:            5

# About/contact
author:
  name:              Li
  url:               https://qmby.github.com
  email:             nvben500@163.com

# Custom vars
version:             1.0.0
